"""crear_tabla_registros_feria

Revision ID: 620cdcf3d1b5
Revises: 
Create Date: 2025-02-14 21:21:54.812010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620cdcf3d1b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_feria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nit', sa.String(length=255), nullable=True),
    sa.Column('nombre_empresa', sa.String(length=255), nullable=False),
    sa.Column('razonSocial', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=255), nullable=True),
    sa.Column('tipoEmpresa', sa.String(length=255), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('sitio_web', sa.String(length=255), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=255), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=False),
    sa.Column('documentos', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estado', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registros_feria_estado'), 'registros_feria', ['estado'], unique=False)
    op.create_index(op.f('ix_registros_feria_fecha_registro'), 'registros_feria', ['fecha_registro'], unique=False)
    op.create_index(op.f('ix_registros_feria_id'), 'registros_feria', ['id'], unique=False)
    op.create_index(op.f('ix_registros_feria_nit'), 'registros_feria', ['nit'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_feria_nit'), table_name='registros_feria')
    op.drop_index(op.f('ix_registros_feria_id'), table_name='registros_feria')
    op.drop_index(op.f('ix_registros_feria_fecha_registro'), table_name='registros_feria')
    op.drop_index(op.f('ix_registros_feria_estado'), table_name='registros_feria')
    op.drop_table('registros_feria')
    # ### end Alembic commands ###
