"""add_certificado_column

Revision ID: 9a0e501dd982
Revises: c9826cc7b104
Create Date: 2025-02-23 19:12:48.153797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0e501dd982'
down_revision: Union[str, None] = 'c9826cc7b104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_feria', sa.Column('ruta_certificado', sa.String(255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registros_feria', 'ruta_certificado')
    # ### end Alembic commands ###
